name: Psalm Security Analysis

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: foo.sarif
